export const GET_PRODUCTINFO = "GET_PRODUCTINFO";
export const GET_SORTEDDATA = "GET_SORTEDDATA";
export const SEARCH_INFO = "SEARCH_INFO";
export const GET_DETAILPRODUCTINFO = "GET_DETAILPRODUCTINFO";
